### ISSUE TITLE
[Feature] TopicInfoAttribute 

### ISSUE THREAD

**Issue by Alexandr-Pletnev** [event-driven-dotnet/EventDriven.EventBus.Abstractions#5]
In order to publish or subscribe to some topic it requires to provide a TopicName or/and Prefix and Suffix as a parameters. 
 
E.g. for publishing: 
```csharp
await _eventBus.PublishAsync(@event, topic: "event-name", prefix: "foo", suffix: "v1");
```

E.g. for subscribing:
```csharp
_eventBus?.Subscribe(myHandler, topic: "event-name", prefix: "foo", suffix: "v1");
```

In this way a developer has to decide how to deal with a Topic Name, Prefix and Suffix, especially across the code in a distributed system.
 
There are few possible approaches:

1. Using hard-coded values (like on screens above) -  it is not the best way (without comments).
2. Using Constants - this approach also has some flaws, see below.
3. Using attributes - it is my suggestion, see below.

**Using constants**

This approach has some flaws, e.g.:

- For publishing and subscribing developer always should pass TopicName, Prefix and Suffix explicitly. This is not very convenient.
- To describe a topic info like Name, Prefix and Suffix developer has to implement a separate class with constants for each IntegrationEvent. It is a separate file which is stored in a different place and such implementation might not be obvious. Especially if developer has a lot of events and some of them have more than 1 version of the same event.

Usage example:
```csharp
await _eventBus.PublishAsync(integrationEvent, MyTopic.Name, MyTopic.Prefix, MyTopic.Suffix);
```

**Using approach based on attributes**

To work with Events publishing and subscribing in more convenient way I want to suggest an approach via Attribute way.
 
This approach has a set of advantages:

- For publishing and subscribing a developer will have a special extensions (syntax sugar) and doesn’t have to pass a Topic Name, Prefix and Suffix explicitly, just pass event or handler itself.
- Describing topic info will be as attribute at the same class with event itself.

It will looks like: 
 
Declaring topic for Integration event:
```csharp
[TopicInfo(Name: "my-topic", Prefix: "my-prefix", Suffix: "v1")]
public record MyIntegrationEvent(Data MyData) : IntegrationEvent;
```

Code implementation of attribute is very simple and clear:
```csharp
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface)]
public class TopicInfoAttribute : Attribute
{
    public TopicInfoAttribute(string topic, string? prefix = null, string? suffix = null)
    {
        if (string.IsNullOrWhiteSpace(topic)) throw new ArgumentNullException(nameof(topic));

        Topic = topic;
        Prefix = prefix;
        Suffix = suffix;
    }

    public string Topic { get; init; }

    public string? Prefix { get; init; }

    public string? Suffix { get; init; }
}
```
 
Also adding extensions for EventBus, will simplify a publishing into the event bus and subscribing as well.
Please let me know if that approach works for you and I can update the code with attributes proposed?

**Comment by tonysneed** [comment]
@Alexandr-Pletnev  Please submit a pull request with your proposed changes. Try to follow the [contributing guidelines](https://github.com/event-driven-dotnet/.github/blob/b390d32b86c222a6295cf0ca87a0f8d445ad2dbd/CONTRIBUTING.md).

**Comment by tonysneed** [comment]
@Alexandr-Pletnev Thanks for submitting this issue. First, here are some tips for contributing to the project.

- Do not paste images of code in your issue or in conversations. Rather, use Markdown to add code. This makes for easier reading and allows for selecting and copying the code. Follow these [guidelines](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for using Markdown with GitHub. The handy toolbar in the text editor should also help. 😄 
  - **Note**: _Observe how I have edited your code snippets in the above issue._
- It is not necessary to add a lot of code to your issue. Rather, create a pull request that contains your proposed code changes. It doesn't matter if you have not finished your contribution. Mark the PR as a Draft, so that we can have a conversation in the pull request about your code.

Second, here are my thoughts on the content of your proposal.

- I like the idea of using a `TopicInfoAttribute` to indicate the topic name, prefix and suffix.
- The result of using the attribute should be the same as passing these values explicitly.
- The topic name in the attribute should be optional, in which case the name is inferred to be either the event type name or the handler topic name.
- Instead of writing extension methods off `IEventBus`, you should add a private `GetTopicFromAttribute` method to the `EventBus` class that returns `TopicInfoAttribute?`. If the attribute is not present, the method should return `null`.
- Call `GetTopicFromAttribute` from both overloads of `GetTopicName`. If the method returns `null`, use the `topic`, `prefix` and `suffix` parameters. Otherwise, pass these values from the `TopicInfoAttribute` to the `FormatTopicName` method.

I am looking forward to your contribution. Thank you.
